name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: "Check"
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: "git clone"
        uses: actions/checkout@v1
      - name: "setup jdk"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: "./gradlew build"
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
        env:
          CI: true
      - name: "coveralls"
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestReport coveralls
        env:
          CI: true
